services:
  city-db:
    image: postgres:16
    container_name: city-db
    environment:
      POSTGRES_DB: city_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d city_db"]
      interval: 5s
      timeout: 5s
      retries: 20

  city-service:
    build:
      context: ./city-catalog-service
      dockerfile: Dockerfile
    container_name: city-service
    depends_on:
      city-db:
        condition: service_healthy
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://city-db:5432/city_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234