version: "3.9"

services:

  # =========================
  # AUTH DATABASE
  # =========================
  auth-db:
    image: postgres:16
    container_name: auth-db
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 5558
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d auth_db"]
      interval: 5s
      timeout: 5s
      retries: 20

  # =========================
  # AUTH SERVICE
  # =========================
  auth-service:
    build:
      context: ./auth-profile-service
      dockerfile: Dockerfile
    container_name: auth-service
    depends_on:
      auth-db:
        condition: service_healthy
    ports:
      - "8084:8084"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      JWT_SECRET: 0v0gJHq7OqJx9nQb0m2Jwq9s0xk6cV8vHcY0kJt9bQw=
      SPRING_DATASOURCE_URL: jdbc:postgresql://auth-db:5432/auth_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 5558

  # =========================
  # ROUTE DATABASE
  # =========================
  route-db:
    image: postgis/postgis:16-3.4
    container_name: route-db
    environment:
      POSTGRES_DB: route_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 5558
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d route_db"]
      interval: 5s
      timeout: 5s
      retries: 20

  # =========================
  # REDIS (для оффлайн маршрутов)
  # =========================
  redis:
    image: redis:7
    container_name: travel-redis
    ports:
      - "6379:6379"

  # =========================
  # ROUTE PLANNING SERVICE
  # =========================
  route-service:
    build:
      context: ./route-planning-service
      dockerfile: Dockerfile
    container_name: route-service
    depends_on:
      route-db:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: docker

      # PostgreSQL
      SPRING_DATASOURCE_URL: jdbc:postgresql://route-db:5432/route_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 5558

      # Redis
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379

      # Если есть Feign для poi-service
      APP_POI_SERVICE_URL: http://poi-service:8081


    restart: unless-stopped
  # =========================
  # PERSONALIZATION DATABASE
  # =========================
  personalization-db:
    image: postgres:16
    container_name: personalization-db
    environment:
      POSTGRES_DB: personalization_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 5558
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d personalization_db"]
      interval: 5s
      timeout: 5s
      retries: 20

  # =========================
  # PERSONALIZATION SERVICE
  # =========================
  personalization-service:
    build:
      context: ./personalization-history-service
      dockerfile: Dockerfile
    container_name: personalization-service
    depends_on:
      personalization-db:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "8085:8085"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SERVER_PORT: 8085

      DB_URL: jdbc:postgresql://personalization-db:5432/personalization_db
      DB_USERNAME: postgres
      DB_PASSWORD: 5558

      REDIS_HOST: redis
      REDIS_PORT: 6379
  # =========================
  # NOTIFICATION DATABASE
  # =========================
  notification-db:
    image: postgres:16
    container_name: notification-db
    environment:
      POSTGRES_DB: notification_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 5558
    ports:
      - "5435:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d notification_db" ]
      interval: 5s
      timeout: 5s
      retries: 20

  # =========================
  # RABBITMQ
  # =========================
  rabbitmq:
    image: rabbitmq:3-management
    container_name: travel-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: [ "CMD-SHELL", "rabbitmq-diagnostics -q ping" ]
      interval: 10s
      timeout: 5s
      retries: 20

  # =========================
  # NOTIFICATION SERVICE
  # =========================
  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    container_name: notification-service
    depends_on:
      notification-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "8086:8086"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SERVER_PORT: 8086

      # PostgreSQL
      DB_URL: jdbc:postgresql://notification-db:5432/notification_db
      DB_USERNAME: postgres
      DB_PASSWORD: 5558

      # Redis
      REDIS_HOST: redis
      REDIS_PORT: 6379

      # RabbitMQ
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest

      # Mail (если реально не настроено — лучше выключить)
      NOTIFICATION_EMAIL_ENABLED: "false"
      MAIL_USERNAME: ""
      MAIL_PASSWORD: ""
